# Generated by Django 4.0.5 on 2022-06-20 15:59

from django.db import migrations
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='bg_image',
            field=sorl.thumbnail.fields.ImageField(default='bg_image/back_default.jpg', upload_to='bg_image'),
        ),
    ]
